"""Versioned, user-facing glossary derived from the product vocabulary."""

from __future__ import annotations

from typing import Any


GLOSSARY_VERSION = "1.0.0"


_TERMS: tuple[dict[str, Any], ...] = (
    {
        "term_id": "breakout",
        "name": "突破",
        "aliases": ["breakout", "breakout_v1"],
        "category": "strategy",
        "plain_definition": "價格有效越過前方壓力或近期高點的條件式型態。",
        "use": "用來描述可能在下一個交易日執行的突破條件，不代表已成交。",
        "how_to_read": "同時查看觸發價、失效價、目標與資料完整度。",
        "limitations": "若前 20 日價格、量能、族群或籌碼資料不完整，系統會採資料不足或觀察。",
        "related": ["pullback", "rr", "t_plus_1", "data_incomplete"],
        "version": GLOSSARY_VERSION,
    },
    {
        "term_id": "pullback",
        "name": "回踩",
        "aliases": ["pullback", "pullback_v1"],
        "category": "strategy",
        "plain_definition": "上升結構中價格回到預定支撐區，等待重新轉強的條件。",
        "use": "用來標示回踩區間與重新站回的觀察條件。",
        "how_to_read": "區分回踩區、觸發價與失效／停損價；沒有完整 MA 或日數不能下結論。",
        "limitations": "不是預測價格一定反彈，也不等同於立即進場。",
        "related": ["ma20", "ma60", "support", "breakout"],
        "version": GLOSSARY_VERSION,
    },
    {
        "term_id": "ma20",
        "name": "MA20",
        "aliases": ["20 日均線"],
        "category": "technical",
        "plain_definition": "最近 20 個有效交易日收盤價的移動平均。",
        "use": "作為短中期趨勢與回踩條件的參考。",
        "how_to_read": "需確認 20 個有效交易日和公司行動基準一致。",
        "limitations": "單一均線不代表趨勢必然延續。",
        "related": ["ma60", "pullback"],
        "version": GLOSSARY_VERSION,
    },
    {
        "term_id": "ma60",
        "name": "MA60",
        "aliases": ["60 日均線"],
        "category": "technical",
        "plain_definition": "最近 60 個有效交易日收盤價的移動平均。",
        "use": "用於確認較長一點的趨勢背景。",
        "how_to_read": "資料少於 60 個有效交易日時不能視為完整。",
        "limitations": "不包含基本面或事件風險。",
        "related": ["ma20", "data_quality"],
        "version": GLOSSARY_VERSION,
    },
    {
        "term_id": "atr",
        "name": "ATR",
        "aliases": ["平均真實波幅"],
        "category": "technical",
        "plain_definition": "以近期高低價與跳空計算的波動幅度指標。",
        "use": "協助檢查停損距離與風險報酬是否合理。",
        "how_to_read": "波動越大，價位區間通常需要更寬；仍須看策略門檻。",
        "limitations": "不是方向指標，不能單獨產生交易建議。",
        "related": ["support", "rr"],
        "version": GLOSSARY_VERSION,
    },
    {
        "term_id": "support",
        "name": "支撐／失效價",
        "aliases": ["support", "invalid_price", "stop_price"],
        "category": "strategy",
        "plain_definition": "價格跌破後，原本的條件假設不再成立的界線。",
        "use": "用來界定策略失效與持倉風險。",
        "how_to_read": "失效價和停損價是不同欄位，前者是策略條件，後者可為持倉設定。",
        "limitations": "遇停牌、除權息或無法比價時不能硬算觸發。",
        "related": ["target", "rr", "incomparable"],
        "version": GLOSSARY_VERSION,
    },
    {
        "term_id": "target",
        "name": "目標價",
        "aliases": ["target_1", "target_2"],
        "category": "strategy",
        "plain_definition": "在風險驗證中預先定義的價格目標。",
        "use": "和失效價一起檢查風險報酬，不是保證價格。",
        "how_to_read": "只有價位與基準完整且 RR 達門檻時才顯示為有效。",
        "limitations": "不代表一定會到達，也不包含交易成本以外的所有風險。",
        "related": ["support", "rr"],
        "version": GLOSSARY_VERSION,
    },
    {
        "term_id": "rr",
        "name": "風險報酬比 RR",
        "aliases": ["risk/reward", "RR"],
        "category": "strategy",
        "plain_definition": "可期待的目標距離相對於失效／停損風險距離的比例。",
        "use": "canonical 價位驗證至少要求 RR ≥ 1.5。",
        "how_to_read": "低於門檻時是無效價位，不應包裝成可執行訊號。",
        "limitations": "比例不會消除跳空、流動性或執行風險。",
        "related": ["target", "support"],
        "version": GLOSSARY_VERSION,
    },
    {
        "term_id": "volume_ratio",
        "name": "量能比",
        "aliases": ["volume ratio", "turnover"],
        "category": "technical",
        "plain_definition": "當日成交量或成交金額相對於歷史基準的比例。",
        "use": "檢查價格型態是否有足夠交易活動支持。",
        "how_to_read": "先確認分母日數完整且大於零。",
        "limitations": "不能單獨代表買方或賣方方向。",
        "related": ["hot_group", "data_incomplete"],
        "version": GLOSSARY_VERSION,
    },
    {
        "term_id": "institutional_flow",
        "name": "法人籌碼",
        "aliases": ["institutional flow", "三大法人"],
        "category": "chips",
        "plain_definition": "外陸資、投信與自營商的淨買賣超資料。",
        "use": "作為策略與族群的籌碼確認條件。",
        "how_to_read": "必要欄位缺一或有效日數不足，就應標示缺失而非補零。",
        "limitations": "不等同於全部市場參與者的持倉方向。",
        "related": ["margin", "data_quality"],
        "version": GLOSSARY_VERSION,
    },
    {
        "term_id": "margin",
        "name": "融資餘額變化",
        "aliases": ["margin balance", "margin change"],
        "category": "chips",
        "plain_definition": "融資今日餘額相對前一日餘額的變化。",
        "use": "作為槓桿與策略風險確認的一部分。",
        "how_to_read": "前日與今日欄位必須來自正確的官方欄位位置。",
        "limitations": "不能單獨解讀為看多或看空。",
        "related": ["institutional_flow", "leverage"],
        "version": GLOSSARY_VERSION,
    },
    {
        "term_id": "chips",
        "name": "個股籌碼",
        "aliases": ["chips", "chip snapshot"],
        "category": "chips",
        "plain_definition": "單一標的的法人買賣超與融資等官方籌碼資料。",
        "use": "確認策略是否有足夠的交易參與與槓桿資料。",
        "how_to_read": "先看資料日數與欄位是否完整，再解讀方向。",
        "limitations": "籌碼資料不代表全部投資人的未來行為。",
        "related": ["institutional_flow", "margin", "data_quality"],
        "version": GLOSSARY_VERSION,
    },
    {
        "term_id": "foreign_flow",
        "name": "外陸資淨買賣超",
        "aliases": ["foreign institutional flow"],
        "category": "chips",
        "plain_definition": "外陸資在指定交易日的買進減賣出金額或張數。",
        "use": "作為法人籌碼確認的一部分。",
        "how_to_read": "缺值不能當成零；需與投信、自營商欄位一起看。",
        "limitations": "單日淨買賣超不等於持續性趨勢。",
        "related": ["institutional_flow", "chips"],
        "version": GLOSSARY_VERSION,
    },
    {
        "term_id": "trust_flow",
        "name": "投信淨買賣超",
        "aliases": ["investment trust flow"],
        "category": "chips",
        "plain_definition": "投信在指定交易日的買進減賣出金額或張數。",
        "use": "作為法人籌碼確認的一部分。",
        "how_to_read": "缺值不能當成零，需確認有效交易日數。",
        "limitations": "不能單獨代表價格方向或未來績效。",
        "related": ["institutional_flow", "chips"],
        "version": GLOSSARY_VERSION,
    },
    {
        "term_id": "dealer_flow",
        "name": "自營商淨買賣超",
        "aliases": ["dealer flow"],
        "category": "chips",
        "plain_definition": "自營商在指定交易日的買進減賣出金額或張數。",
        "use": "作為法人籌碼確認的一部分。",
        "how_to_read": "缺值不能當成零，並留意自營商組成與期間。",
        "limitations": "不能單獨代表市場共識。",
        "related": ["institutional_flow", "chips"],
        "version": GLOSSARY_VERSION,
    },
    {
        "term_id": "taiex",
        "name": "TAIEX",
        "aliases": ["加權指數", "大盤"],
        "category": "market",
        "plain_definition": "本專案用來比較台股市場相對強弱的官方大盤基準。",
        "use": "計算個股或族群相對大盤的 1／5／20 日報酬。",
        "how_to_read": "沒有同日且完整的 TAIEX 基準時，不能宣稱相對強弱成立。",
        "limitations": "相對強不代表絕對報酬一定為正。",
        "related": ["breadth", "hot_group"],
        "version": GLOSSARY_VERSION,
    },
    {
        "term_id": "breadth",
        "name": "廣度",
        "aliases": ["breadth"],
        "category": "market",
        "plain_definition": "族群中符合比較條件、跑贏或上漲的成員比例。",
        "use": "避免只靠少數股票把整個族群排成熱門。",
        "how_to_read": "查看有效成員分子與分母；不完整時應標 partial。",
        "limitations": "不代表族群內每一檔股票都同步。",
        "related": ["hot_group", "data_quality"],
        "version": GLOSSARY_VERSION,
    },
    {
        "term_id": "hot_group",
        "name": "熱門族群",
        "aliases": ["theme", "group"],
        "category": "market",
        "plain_definition": "在同一比較基準下，資料完整且至少有三個有效成員的族群排行。",
        "use": "先發現市場方向，再從中找候選股票；ETF 與公司族群分榜。",
        "how_to_read": "沒有 complete、最低成員數或 TAIEX 基準時不排名。",
        "limitations": "排行是研究篩選，不是投資建議。",
        "related": ["taiex", "breadth", "etf"],
        "version": GLOSSARY_VERSION,
    },
    {
        "term_id": "etf",
        "name": "ETF 分類",
        "aliases": ["ETF", "bond ETF", "leveraged ETF"],
        "category": "etf",
        "plain_definition": "依官方 allowlist 與分類保存的交易所交易基金類別。",
        "use": "和公司股票族群分榜，債券／槓桿／反向 ETF 不混入一般公司策略。",
        "how_to_read": "分類缺失時 fail-closed，不以名稱猜測。",
        "limitations": "ETF 的曝險、槓桿與追蹤誤差不同於單一公司股票。",
        "related": ["hot_group", "data_quality"],
        "version": GLOSSARY_VERSION,
    },
    {
        "term_id": "as_of",
        "name": "資料截至",
        "aliases": ["as_of", "data cutoff"],
        "category": "data_quality",
        "plain_definition": "這筆分析允許使用的資料截止日期。",
        "use": "確認訊號與回測沒有讀到未來資料。",
        "how_to_read": "把訊號日、最早 T+1 執行日和資料截止分開看。",
        "limitations": "截至日不保證每個欄位都已完整。",
        "related": ["collected_at", "technical_backtest"],
        "version": GLOSSARY_VERSION,
    },
    {
        "term_id": "collected_at",
        "name": "擷取時間",
        "aliases": ["collected_at"],
        "category": "data_quality",
        "plain_definition": "系統實際保存官方回應的時間。",
        "use": "追蹤資料新鮮度與重跑來源。",
        "how_to_read": "和資料截至日、raw payload hash 一起稽核。",
        "limitations": "較晚擷取不代表資料截至日較新。",
        "related": ["as_of", "raw_provenance"],
        "version": GLOSSARY_VERSION,
    },
    {
        "term_id": "raw_provenance",
        "name": "Raw／來源追溯",
        "aliases": ["raw payload", "provenance"],
        "category": "data_quality",
        "plain_definition": "保存原始回應、hash、來源、endpoint、資料日期與擷取時間的鏈結。",
        "use": "讓每筆衍生資料可回到官方證據。",
        "how_to_read": "優先查看 raw payload 是否存在且沒有 orphan link。",
        "limitations": "raw 存在不代表欄位解析或資料完整。",
        "related": ["data_quality", "collected_at"],
        "version": GLOSSARY_VERSION,
    },
    {
        "term_id": "data_quality",
        "name": "資料品質",
        "aliases": ["complete", "partial", "missing", "data_incomplete", "fail-closed"],
        "category": "data_quality",
        "plain_definition": "對資料是否足以支持特定用途的明確狀態。",
        "use": "決定是否排名、產生行動或只能顯示觀察。",
        "how_to_read": "complete 才可進入對應規則；partial／missing 要看缺少欄位。",
        "limitations": "品質是用途相依的，行情完整不代表籌碼完整。",
        "related": ["as_of", "raw_provenance", "incomparable"],
        "version": GLOSSARY_VERSION,
    },
    {
        "term_id": "decision_summary",
        "name": "行動摘要",
        "aliases": ["DecisionSummary", "action card"],
        "category": "strategy",
        "plain_definition": "把同一檔股票同一資料日的策略結果、資料品質與持倉風險合併成一張可讀摘要。",
        "use": "首頁與行動頁先回答現在做什麼、依據什麼、缺什麼。",
        "how_to_read": "先看狀態與優先級，再看觸發／失效／目標和證據。",
        "limitations": "它是研究介面，不是個人化投資建議。",
        "related": ["tracking", "signal_row", "data_quality"],
        "version": GLOSSARY_VERSION,
    },
    {
        "term_id": "t_plus_1",
        "name": "T+1",
        "aliases": ["earliest execution"],
        "category": "tracking",
        "plain_definition": "訊號在 T 日收盤形成後，最早可嘗試執行的下一個有效交易日。",
        "use": "避免使用訊號日收盤價假裝成交。",
        "how_to_read": "執行價需保留當期 raw 價格與滑價假設。",
        "limitations": "不保證成交，停牌或缺 bar 時不可比。",
        "related": ["tracking", "settlement", "incomparable"],
        "version": GLOSSARY_VERSION,
    },
    {
        "term_id": "tracking",
        "name": "追蹤",
        "aliases": ["tracking", "evaluation"],
        "category": "tracking",
        "plain_definition": "在訊號後逐一檢查價格、籌碼與條件是否觸發的過程。",
        "use": "產生 T+5／T+20 的可比或不可比結果。",
        "how_to_read": "先看 comparable，再解讀報酬；停牌與公司行動可能使結果不可比。",
        "limitations": "技術追蹤樣本不足時不能當研究證據。",
        "related": ["settlement", "incomparable", "technical_backtest"],
        "version": GLOSSARY_VERSION,
    },
    {
        "term_id": "settlement",
        "name": "結算",
        "aliases": ["SignalSettlement"],
        "category": "tracking",
        "plain_definition": "在指定交易日 horizon 對訊號結果做一次可稽核結論。",
        "use": "保存 T+5 與 T+20 的狀態、日期、報酬或不可比原因。",
        "how_to_read": "不可比不等於虧損，不能計入勝率分母。",
        "limitations": "短資料窗只足以技術驗證，不能支持策略採用結論。",
        "related": ["tracking", "incomparable"],
        "version": GLOSSARY_VERSION,
    },
    {
        "term_id": "incomparable",
        "name": "不可比",
        "aliases": ["incomparable"],
        "category": "data_quality",
        "plain_definition": "因停牌、公司行動、缺少必要交易日或 cutoff 而不能公平計算結果。",
        "use": "阻止系統把不連續或未完成資料當成報酬。",
        "how_to_read": "查看明確 incomparable_reason，不把它當正負報酬。",
        "limitations": "不可比本身不是市場方向判斷。",
        "related": ["settlement", "t_plus_1", "data_quality"],
        "version": GLOSSARY_VERSION,
    },
    {
        "term_id": "technical_backtest",
        "name": "技術回測",
        "aliases": ["technical backtest", "walk-forward", "OOS"],
        "category": "tracking",
        "plain_definition": "按日期重播固定版本規則、只使用當時可得資料的驗證流程。",
        "use": "檢查資料管線與規則執行，不等於參數最佳化或獨立 OOS 證據。",
        "how_to_read": "三個月或樣本不足時應標 insufficient_sample。",
        "limitations": "尚不足以支持勝率、採用或未來績效結論。",
        "related": ["as_of", "tracking", "settlement"],
        "version": GLOSSARY_VERSION,
    },
)


def glossary_terms(q: str | None = None, category: str | None = None) -> list[dict[str, Any]]:
    rows = [dict(term) for term in _TERMS]
    if q and q.strip():
        needle = q.strip().casefold()
        rows = [
            row
            for row in rows
            if needle in row["term_id"].casefold()
            or needle in row["name"].casefold()
            or any(needle in alias.casefold() for alias in row["aliases"])
        ]
    if category:
        rows = [row for row in rows if row["category"] == category]
    return rows
