import type { GlossaryTerm } from './types'

// A local copy keeps the glossary usable while the API is unavailable.  The
// backend exposes the same versioned terms for audit and other clients.
export const GLOSSARY: GlossaryTerm[] = [
  {
    term_id: 'breakout', name: '突破', aliases: ['breakout'], category: 'strategy',
    plain_definition: '價格有效越過近期壓力或高點的條件式型態。',
    use: '描述可能在下一交易日執行的條件，不代表已成交。',
    how_to_read: '同時看觸發價、失效價、目標與資料完整度。',
    limitations: '資料不足時不會形成可執行結論。', related: ['rr', 't_plus_1'], version: '1.0.0',
  },
  {
    term_id: 'pullback', name: '回踩', aliases: ['pullback'], category: 'strategy',
    plain_definition: '價格回到預定支撐區、等待重新轉強的條件。',
    use: '標示回踩區間與重新站回的觀察條件。',
    how_to_read: '區分回踩區、觸發價與失效價。',
    limitations: '不是價格一定反彈，也不是立即進場。', related: ['ma20', 'ma60'], version: '1.0.0',
  },
  {
    term_id: 'ma20', name: 'MA20', aliases: ['20 日均線'], category: 'technical',
    plain_definition: '最近 20 個有效交易日收盤價的移動平均。',
    use: '參考短中期趨勢與回踩條件。',
    how_to_read: '確認日數完整且公司行動基準一致。',
    limitations: '單一均線不代表趨勢必然延續。', related: ['ma60'], version: '1.0.0',
  },
  {
    term_id: 'ma60', name: 'MA60', aliases: ['60 日均線'], category: 'technical',
    plain_definition: '最近 60 個有效交易日收盤價的移動平均。',
    use: '確認較長期的趨勢背景。',
    how_to_read: '少於 60 個有效交易日時視為不完整。',
    limitations: '不包含基本面或事件風險。', related: ['ma20'], version: '1.0.0',
  },
  {
    term_id: 'atr', name: 'ATR', aliases: ['平均真實波幅'], category: 'technical',
    plain_definition: '以高低價與跳空計算的近期波動幅度指標。',
    use: '協助檢查風險距離。',
    how_to_read: '波動越大，價位區間通常需要更寬。',
    limitations: '不是方向指標，不能單獨產生行動。', related: ['rr'], version: '1.0.0',
  },
  {
    term_id: 'rr', name: '風險報酬比 RR', aliases: ['RR'], category: 'strategy',
    plain_definition: '目標距離相對於失效或停損風險距離的比例。',
    use: '固定規則的價位驗證至少要求 RR ≥ 1.5。',
    how_to_read: '低於門檻時視為無效價位。',
    limitations: '不會消除跳空、流動性或執行風險。', related: ['target', 'support'], version: '1.0.0',
  },
  {
    term_id: 'target', name: '目標價', aliases: ['target_1'], category: 'strategy',
    plain_definition: '風險驗證中預先定義的價格目標。',
    use: '與失效價一起檢查風險報酬。',
    how_to_read: '只有價位與基準完整時顯示為有效。',
    limitations: '不代表一定到達。', related: ['support', 'rr'], version: '1.0.0',
  },
  {
    term_id: 'support', name: '支撐／失效價', aliases: ['invalid_price'], category: 'strategy',
    plain_definition: '跌破後原本條件假設不再成立的界線。',
    use: '界定策略失效與持倉風險。',
    how_to_read: '策略失效價與持倉停損價是不同欄位。',
    limitations: '停牌、除權息或不可比時不能硬算觸發。', related: ['target', 'incomparable'], version: '1.0.0',
  },
  {
    term_id: 'institutional_flow', name: '法人籌碼', aliases: ['三大法人'], category: 'chips',
    plain_definition: '外陸資、投信與自營商的淨買賣超資料。',
    use: '作為策略與族群的籌碼確認。',
    how_to_read: '必要欄位缺一或有效日數不足就標缺失，不補零。',
    limitations: '不等同於所有市場參與者的持倉方向。', related: ['margin', 'data_quality'], version: '1.0.0',
  },
  {
    term_id: 'margin', name: '融資餘額變化', aliases: ['margin change'], category: 'chips',
    plain_definition: '融資今日餘額相對前一日餘額的變化。',
    use: '作為槓桿與風險確認。',
    how_to_read: '前日與今日欄位必須來自正確官方欄位位置。',
    limitations: '不能單獨解讀為看多或看空。', related: ['institutional_flow'], version: '1.0.0',
  },
  {
    term_id: 'chips', name: '個股籌碼', aliases: ['chips'], category: 'chips',
    plain_definition: '單一標的的法人買賣超與融資等官方籌碼資料。',
    use: '確認策略是否有足夠的交易參與與槓桿資料。',
    how_to_read: '先看資料日數與欄位是否完整，再解讀方向。',
    limitations: '籌碼資料不代表全部投資人的未來行為。', related: ['institutional_flow', 'margin'], version: '1.0.0',
  },
  {
    term_id: 'foreign_flow', name: '外陸資淨買賣超', aliases: ['foreign institutional flow'], category: 'chips',
    plain_definition: '外陸資在指定交易日的買進減賣出金額或張數。',
    use: '作為法人籌碼確認的一部分。',
    how_to_read: '缺值不能當成零；需與投信、自營商欄位一起看。',
    limitations: '單日淨買賣超不等於持續性趨勢。', related: ['institutional_flow', 'chips'], version: '1.0.0',
  },
  {
    term_id: 'trust_flow', name: '投信淨買賣超', aliases: ['investment trust flow'], category: 'chips',
    plain_definition: '投信在指定交易日的買進減賣出金額或張數。',
    use: '作為法人籌碼確認的一部分。',
    how_to_read: '缺值不能當成零，需確認有效交易日數。',
    limitations: '不能單獨代表價格方向或未來績效。', related: ['institutional_flow', 'chips'], version: '1.0.0',
  },
  {
    term_id: 'dealer_flow', name: '自營商淨買賣超', aliases: ['dealer flow'], category: 'chips',
    plain_definition: '自營商在指定交易日的買進減賣出金額或張數。',
    use: '作為法人籌碼確認的一部分。',
    how_to_read: '缺值不能當成零，並留意自營商組成與期間。',
    limitations: '不能單獨代表市場共識。', related: ['institutional_flow', 'chips'], version: '1.0.0',
  },
  {
    term_id: 'taiex', name: 'TAIEX', aliases: ['大盤'], category: 'market',
    plain_definition: '本專案比較台股相對強弱的官方大盤基準。',
    use: '計算個股或族群 1／5／20 日相對報酬。',
    how_to_read: '缺少同日完整基準時不能宣稱相對強弱。',
    limitations: '相對強不代表絕對報酬為正。', related: ['breadth', 'hot_group'], version: '1.0.0',
  },
  {
    term_id: 'breadth', name: '廣度', aliases: ['breadth'], category: 'market',
    plain_definition: '族群內符合比較條件或上漲的成員比例。',
    use: '避免少數股票代表整個族群。',
    how_to_read: '查看有效成員分子與分母。',
    limitations: '不代表每檔成員同步。', related: ['hot_group'], version: '1.0.0',
  },
  {
    term_id: 'hot_group', name: '熱門族群', aliases: ['theme'], category: 'market',
    plain_definition: '資料完整且至少三個有效成員的族群排行。',
    use: '先發現市場方向，再找候選股票；ETF 獨立分榜。',
    how_to_read: '沒有 complete、最低成員數或 TAIEX 基準就不排名。',
    limitations: '排行是研究篩選，不是投資建議。', related: ['taiex', 'breadth', 'etf'], version: '1.0.0',
  },
  {
    term_id: 'etf', name: 'ETF 分類', aliases: ['ETF'], category: 'etf',
    plain_definition: '依官方 allowlist 與分類保存的交易所交易基金類別。',
    use: '和公司族群分榜，債券／槓桿／反向 ETF 不混入一般公司策略。',
    how_to_read: '分類缺失時 fail-closed，不靠名稱猜測。',
    limitations: 'ETF 曝險與追蹤誤差不同於單一公司。', related: ['hot_group'], version: '1.0.0',
  },
  {
    term_id: 'data_quality', name: '資料品質', aliases: ['complete', 'partial', 'missing'], category: 'data_quality',
    plain_definition: '資料是否足以支持特定用途的明確狀態。',
    use: '決定是否排名、產生行動或只能觀察。',
    how_to_read: '查看缺少欄位；complete 才可進入對應規則。',
    limitations: '品質是用途相依的，行情完整不代表籌碼完整。', related: ['as_of', 'incomparable'], version: '1.0.0',
  },
  {
    term_id: 'decision_summary', name: '行動摘要', aliases: ['DecisionSummary'], category: 'strategy',
    plain_definition: '把策略結果、資料品質與持倉風險合併成一張可讀摘要。',
    use: '先回答現在做什麼、依據什麼、缺什麼。',
    how_to_read: '先看狀態和優先級，再看價位與證據。',
    limitations: '是研究介面，不是個人化投資建議。', related: ['tracking', 'data_quality'], version: '1.0.0',
  },
  {
    term_id: 't_plus_1', name: 'T+1', aliases: ['earliest execution'], category: 'tracking',
    plain_definition: 'T 日收盤訊號後最早可嘗試執行的下一有效交易日。',
    use: '避免使用訊號日收盤價假裝成交。',
    how_to_read: '執行價保留當期 raw 價格與滑價假設。',
    limitations: '不保證成交，停牌或缺 bar 時不可比。', related: ['tracking', 'settlement'], version: '1.0.0',
  },
  {
    term_id: 'tracking', name: '追蹤／結算', aliases: ['tracking', 'settlement'], category: 'tracking',
    plain_definition: '在訊號後檢查條件並保存 T+5／T+20 結果的流程。',
    use: '區分可比結果與不可比資料。',
    how_to_read: '先看 comparable，不可比不等於虧損。',
    limitations: '短資料窗不能支持策略採用結論。', related: ['incomparable', 't_plus_1'], version: '1.0.0',
  },
  {
    term_id: 'incomparable', name: '不可比', aliases: ['incomparable'], category: 'data_quality',
    plain_definition: '因停牌、公司行動、缺日或 cutoff 不能公平計算結果。',
    use: '阻止不連續資料被當成報酬。',
    how_to_read: '查看明確原因，不計入勝率分母。',
    limitations: '不是市場方向判斷。', related: ['tracking', 'settlement'], version: '1.0.0',
  },
]
